output "codecommit_clone_url" {
  value       = aws_codecommit_repository.app.clone_url_http
  description = "CodeCommit HTTPS clone URL"
}

output "codepipeline_name" {
  value       = aws_codepipeline.app.name
  description = "Name of the automated pipeline"
}

output "ecr_repository_url" {
  value       = aws_ecr_repository.app.repository_url
  description = "ECR repository URI"
}

output "artifacts_bucket" {
  value       = aws_s3_bucket.artifacts.bucket
  description = "S3 bucket storing pipeline artifacts"
}

output "compliance_bucket" {
  value       = aws_s3_bucket.compliance.bucket
  description = "S3 bucket storing compliance evidences"
}

output "compliance_bucket_kms_key_id" {
  value       = aws_kms_key.compliance.key_id
  description = "KMS key securing compliance evidence"
}

output "eks_cluster_name" {
  value       = aws_eks_cluster.this.name
  description = "EKS cluster name"
}

output "eks_deploy_role_arn" {
  value       = aws_iam_role.eks_deploy.arn
  description = "Role assumed for kubectl apply"
}

output "alb_dns_name" {
  value       = aws_lb.main.dns_name
  description = "Application Load Balancer DNS"
}

output "alb_target_group_arn" {
  value       = aws_lb_target_group.app.arn
  description = "Target group ARN used by the ingress TargetGroupBinding"
}

output "alb_security_group_id" {
  value       = aws_security_group.alb.id
  description = "Security group protecting the ALB"
}

output "alb_certificate_arn_in_use" {
  value       = local.alb_certificate_arn
  description = "Certificate ARN attached to the ALB listener (self-signed when ACM ARN not provided)"
}

output "alb_self_signed_certificate_expiration" {
  value       = local.alb_self_signed_expiration
  description = "Timestamp when the autogenerated certificate expires. Empty when a customer ACM certificate is supplied."
}

output "cognito_user_pool_id" {
  value       = aws_cognito_user_pool.demo.id
  description = "Cognito user pool id"
}

output "cognito_user_pool_client_id" {
  value       = aws_cognito_user_pool_client.demo.id
  description = "Cognito app client id"
}

output "cognito_domain" {
  value       = aws_cognito_user_pool_domain.demo.domain
  description = "Hosted Cognito domain prefix"
}

output "sns_alerts_topic_arn" {
  value       = aws_sns_topic.alerts.arn
  description = "SNS topic ARN for CloudWatch alarm notifications"
}

output "cloudwatch_alarms" {
  value = {
    codepipeline_failures = aws_cloudwatch_metric_alarm.codepipeline_failures.alarm_name
    alb_5xx               = aws_cloudwatch_metric_alarm.alb_5xx.alarm_name
    alb_target_5xx        = aws_cloudwatch_metric_alarm.alb_target_5xx.alarm_name
    alb_unhealthy_hosts   = aws_cloudwatch_metric_alarm.alb_unhealthy_hosts.alarm_name
    eks_api_errors        = aws_cloudwatch_metric_alarm.eks_api_errors.alarm_name
  }
  description = "Map of CloudWatch alarm names for monitoring"
}

output "waf_web_acl_arn" {
  value       = var.enable_waf ? aws_wafv2_web_acl.alb[0].arn : null
  description = "WAF Web ACL ARN (null if WAF is disabled)"
}

output "eks_addons" {
  value = {
    vpc_cni    = aws_eks_addon.vpc_cni.addon_name
    kube_proxy = aws_eks_addon.kube_proxy.addon_name
    coredns    = aws_eks_addon.coredns.addon_name
  }
  description = "EKS managed add-ons configuration"
}
